### ISSUE TITLE
cannot create .jar

### ISSUE THREAD

**Issue by jviure** [aquenneville/synology-dsm-file-duplicate-remover#1]
Hi!  can you post or send me the .jar resultant file? I can't achieve it! :(   if I try to create the .jar with "mvn package" I obtain this error: 

"Error: Could not find or load main class src.main.java.syno.fileduplicateremover.SynoFileDuplicateRemover"

Some idea? thanks! :)

**Comment by aquenneville** [comment]
Hi, I am using Maven v.3.3.1. No issues. Have you tried from the root of the project?
[synofileduplicateremover-0.0.1-SNAPSHOT.zip](https://github.com/aquenneville/synology-dsm-file-duplicate-remover/files/3517290/synofileduplicateremover-0.0.1-SNAPSHOT.zip)
Just change the extension back to .jar
